spring.application.name=demo2
server.port=8088


#mysql
spring.datasource.url = jdbc:mysql://localhost:23306/mydb?useSSL=false&server\
  Timezone=UTC&characterEncoding=UTF-8
spring.datasource.username = root
spring.datasource.password = Littleboy1s
spring.datasource.driver-class-name = com.mysql.jdbc.Driver

#MyBatis
mybatis-plus.type-aliases-package=org.example.demo.model
mybatis.configuration.map-underscore-to-camel-case = true